import { Octokit } from '@octokit/rest';
import { ClientData } from '../types/client';
import { createLogger } from '../utils/logger';
import { fileManager } from '../utils/file-manager';
import fs from 'fs/promises';
import path from 'path';

const logger = createLogger('GitHubManager');

export class GitHubManager {
  private octokit: Octokit;
  private username: string;

  constructor() {
    this.octokit = new Octokit({
      auth: process.env.GITHUB_TOKEN,
    });
    this.username = process.env.GITHUB_USERNAME || '';
  }

  /**
   * Create GitHub repository for client
   */
  async createRepository(clientData: ClientData): Promise<{ repoUrl: string; cloneUrl: string }> {
    try {
      const { businessName, clientId } = clientData.info;
      const repoName = this.sanitizeRepoName(businessName);

      logger.info('Creating GitHub repository', { repoName });

      // Create repository
      const response = await this.octokit.repos.createForAuthenticatedUser({
        name: repoName,
        description: `Website for ${businessName} - Generated by Attom`,
        private: false,
        auto_init: true,
      });

      const repoUrl = response.data.html_url;
      const cloneUrl = response.data.clone_url;

      logger.success('GitHub repository created', { repoUrl });

      // Update client data
      clientData.deployment.github = {
        repoUrl,
        branch: 'main',
      };

      await fileManager.updateClientInfo(clientId, clientData);

      // Log action
      await fileManager.logAction(clientId, 'github-repo-created', {
        repoUrl,
        repoName,
      });

      return { repoUrl, cloneUrl };
    } catch (error) {
      logger.error('Failed to create GitHub repository', error);
      throw error;
    }
  }

  /**
   * Upload website files to repository
   */
  async uploadFiles(
    clientData: ClientData,
    filesDir: string
  ): Promise<void> {
    try {
      const repoName = this.sanitizeRepoName(clientData.info.businessName);

      logger.info('Uploading files to GitHub', { repoName });

      // Read all files from directory
      const files = await this.readDirectoryRecursive(filesDir);

      // Upload files one by one (or in batches)
      for (const file of files) {
        const content = await fs.readFile(file.path);
        const base64Content = content.toString('base64');

        await this.octokit.repos.createOrUpdateFileContents({
          owner: this.username,
          repo: repoName,
          path: file.relativePath,
          message: `Add ${file.relativePath}`,
          content: base64Content,
        });

        logger.info(`Uploaded: ${file.relativePath}`);
      }

      // Update deployment status
      clientData.deployment.github = {
        ...clientData.deployment.github!,
        lastCommit: new Date().toISOString(),
      };

      await fileManager.updateClientInfo(clientData.info.clientId, clientData);

      logger.success(`Uploaded ${files.length} files to GitHub`);

      // Log action
      await fileManager.logAction(clientData.info.clientId, 'files-uploaded-to-github', {
        filesCount: files.length,
        repoName,
      });
    } catch (error) {
      logger.error('Failed to upload files to GitHub', error);
      throw error;
    }
  }

  /**
   * Read directory recursively
   */
  private async readDirectoryRecursive(
    dir: string,
    baseDir: string = dir
  ): Promise<Array<{ path: string; relativePath: string }>> {
    const files: Array<{ path: string; relativePath: string }> = [];

    const entries = await fs.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        const subFiles = await this.readDirectoryRecursive(fullPath, baseDir);
        files.push(...subFiles);
      } else {
        files.push({
          path: fullPath,
          relativePath: path.relative(baseDir, fullPath),
        });
      }
    }

    return files;
  }

  /**
   * Sanitize repository name
   */
  private sanitizeRepoName(businessName: string): string {
    return businessName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
  }

  /**
   * Enable GitHub Pages
   */
  async enableGitHubPages(clientData: ClientData): Promise<string> {
    try {
      const repoName = this.sanitizeRepoName(clientData.info.businessName);

      logger.info('Enabling GitHub Pages', { repoName });

      await this.octokit.repos.createPagesSite({
        owner: this.username,
        repo: repoName,
        source: {
          branch: 'main',
          path: '/',
        },
      });

      const pagesUrl = `https://${this.username}.github.io/${repoName}`;

      logger.success('GitHub Pages enabled', { pagesUrl });

      return pagesUrl;
    } catch (error) {
      logger.error('Failed to enable GitHub Pages', error);
      throw error;
    }
  }
}

export const githubManager = new GitHubManager();
